// The reactive mirror of the backend's AppState. Slices match faf-domain.
// Tabs read with `useAppStore(s => s.state.<slice>)` and never mutate directly,
// the only writes are `apply` (from events) and `hydrate` (initial snapshot).

import { create } from "zustand";
import type { AppEvent, AppState } from "../ipc/bindings";
import { EMPTY_REPLAY_QUERY } from "../shared/replayQuery";
import { EMPTY_TRAINING_QUERY } from "../shared/trainingQuery";
import { EMPTY_MAP_QUERY, EMPTY_MOD_QUERY } from "../shared/vaultQuery";
import { EMPTY_CLAN_STATE } from "./reducers/clan";
import { applyEvent } from "./reducer";

const INITIAL: AppState = {
  session: { backendVersion: "", status: "disconnected", offlineAuth: false },
  auth: { status: "loggedOut", player: null, error: null, mode: "account" },
  nav: {
    activeTab: "news",
    mapsSection: "vault",
    modsSection: "vault",
    replaysSection: "online",
    settingsSection: "general",
  },
  notifications: { items: [] },
  chat: {
    status: "disconnected",
    username: "",
    channels: [],
    retainedHistories: [],
    activeChannel: "",
    showJoinsParts: false,
    serverAutoJoin: [],
  },
  clan: EMPTY_CLAN_STATE,
  lobby: {
    status: "disconnected",
    games: [],
    liveGames: [],
    join: { type: "idle" },
    matchmakerQueues: [],
    matchmaking: { type: "idle" },
    party: { ownerId: null, members: [] },
    vetoes: [],
    playMode: "custom",
    availableAvatars: [],
    avatarListStatus: "idle",
    avatarListError: "",
    avatarSelectionStatus: "idle",
    avatarSelectionError: "",
    hostPrefill: null,
  },
  replays: {
    status: { type: "idle" },
    lastWarning: null,
    preparing: null,
    liveTracking: null,
    vault: [],
    vaultStatus: { type: "idle" },
    vaultQuery: EMPTY_REPLAY_QUERY,
    vaultHasMore: false,
    vaultTotalPages: null,
    vaultTotalRecords: null,
    downloadStatus: { type: "idle" },
    featuredMods: [],
    local: [],
    localStatus: { type: "idle" },
    replayDetails: {},
    detailsLoading: null,
    detailsError: null,
    analysis: null,
    analysisLoading: null,
    analysisError: null,
    onlineLookups: {},
    resolvedMaps: {},
    recentMatchmaker: [],
    recentMatchmakerStatus: { type: "idle" },
  },
  maps: {
    vault: [],
    vaultStatus: { type: "idle" },
    vaultProgress: null,
    browse: [],
    browseStatus: { type: "idle" },
    browseQuery: EMPTY_MAP_QUERY,
    browseTotalPages: null,
    browseTotalRecords: null,
    installed: [],
    installedStatus: { type: "idle" },
    installStatus: { type: "idle" },
    visibilityStatus: { type: "idle" },
    matchmakerPools: {},
    matchmakerPoolsStatus: { type: "idle" },
    localPreviews: {},
    localPreviewOrder: [],
  },
  mapGenerator: {
    status: { type: "idle" },
    latestVersion: "",
    availableVersions: [],
    selectedVersion: null,
    optionLists: {
      symmetries: [
        "POINT2", "POINT3", "POINT4", "POINT5", "POINT6", "POINT7", "POINT8", "POINT9",
        "POINT10", "POINT11", "POINT12", "POINT13", "POINT14", "POINT15", "POINT16",
        "XZ", "ZX", "X", "Z", "QUAD", "DIAG", "NONE",
      ],
      styles: [
        "BASIC", "BIG_ISLANDS", "CENTER_LAKE", "DROP_PLATEAU", "FLOODED", "HIGH_RECLAIM",
        "LAND_BRIDGE", "LITTLE_MOUNTAIN", "LOW_MEX", "MOUNTAIN_RANGE", "MULTILEVEL",
        "ONE_ISLAND", "SMALL_ISLANDS", "VALLEY", "RIVERS", "RIVERS_AND_OCEANS",
        "FRACTAL_LAND", "FRACTAL_PLATEAU", "FRACTAL_NAVY", "SETONISH", "FORREST_SOMETHING",
      ],
      terrainStyles: [
        "ACCEL", "BIG_ISLANDS", "CENTER_ISLAND", "CLEAN", "CORRIDOR", "DROP_PLATEAU", "DUAL_GAP",
        "FLOODED", "GAP", "GLACIER", "HILLY", "ISLANDS", "LAND", "LOW_PLATEAU",
        "MOUNTAIN_RANGE", "ONE_ISLAND", "PASSES", "PLATEAU", "RAMP_PLATEAU", "RIVERS",
        "SCARRED", "SLOPE", "TUNDRA", "VALLEY", "WATER",
      ],
      textureStyles: [
        "BRIMSTONE", "DESERT", "FROST", "LUSH", "MARS", "MOON", "SAVANNAH", "STEPPE",
        "TUNDRA", "WONDER",
      ],
      resourceStyles: ["BASIC", "DENSE", "EXPANSIVE", "SPARSE"],
      propStyles: [
        "BASIC", "BOULDERS", "FOREST", "ROCKS", "ROCK_FIELD", "TREE_FIELD", "WRECKAGE",
      ],
    },
    // Mirrors `impl Default for GeneratorOptions` in faf-domain.
    options: {
      version: null,
      spawnCount: 6,
      numTeams: 2,
      mapSize: 512,
      seed: "",
      generationType: "casual",
      symmetry: "",
      symmetries: [],
      style: "",
      styles: [],
      terrainStyle: "",
      terrainStyles: [],
      textureStyle: "",
      textureStyles: [],
      resourceStyle: "",
      resourceStyles: [],
      propStyle: "",
      propStyles: [],
      reclaimDensity: null,
      reclaimDensityMin: null,
      reclaimDensityMax: null,
      resourceDensity: null,
      resourceDensityMin: null,
      resourceDensityMax: null,
      numToGenerate: null,
      debug: false,
      visualize: false,
      previewPath: "",
      outputPath: "",
      commandLineArgs: "",
    },
    previews: {},
    validation: [],
    predictedName: "",
    decoded: {},
    helpText: "",
    presets: [],
    presetSave: null,
  },
  mods: {
    vault: [],
    vaultStatus: { type: "idle" },
    vaultProgress: null,
    browse: [],
    browseStatus: { type: "idle" },
    browseQuery: EMPTY_MOD_QUERY,
    browseTotalPages: null,
    browseTotalRecords: null,
    installed: [],
    installedStatus: { type: "idle" },
    installStatus: { type: "idle" },
    toggleStatus: { type: "idle" },
    downloadSizes: {},
  },
  leaderboard: {
    mode: "ratings",
    ratingLeaderboards: [],
    leagues: [],
    catalogStatus: { type: "idle" },
    ratingQuery: {
      leaderboard: "global",
      page: 1,
      pageSize: 100,
      activeOnly: true,
      updatedAfter: null,
      updatedBefore: null,
      player: "",
      includeFormerNames: false,
    },
    ratingPage: {
      entries: [],
      page: 1,
      pageSize: 100,
      totalPages: 1,
      totalResults: null,
    },
    ratingsStatus: { type: "idle" },
    crossRatings: [],
    selectedLeagueId: null,
    seasons: [],
    seasonsStatus: { type: "idle" },
    selectedSeasonId: null,
    seasonEntries: [],
    tiers: [],
    seasonStatus: { type: "idle" },
  },
  playerCard: {
    open: false,
    requestedLogin: "",
    profile: null,
    profileStatus: "idle",
    profileError: "",
    historyQuery: null,
    history: [],
    historyMaximum: null,
    historyPage: 0,
    historyTotalPages: 1,
    historyStatus: "idle",
    historyError: "",
    matchmakerProfile: null,
    matchmakerProfileStatus: "idle",
    matchmakerProfileError: "",
    partyPlacements: {},
    mapStats: null,
    mapStatsStatus: "idle",
    mapStatsError: "",
    accountLookup: { query: "", matches: [] },
  },
  reporting: {
    open: false,
    playerId: null,
    login: "",
    status: { type: "idle" },
    history: [],
    historyStatus: { type: "idle" },
  },
  reviews: {
    target: null,
    reviews: [],
    summary: { total: 0, averageTenths: 0, counts: [0, 0, 0, 0, 0] },
    status: { type: "idle" },
    submit: { type: "idle" },
  },
  install: {
    gameReady: false,
    replayReady: false,
    gamePending: false,
    replayPending: false,
    checked: false,
    resolved: {
      vaultDir: "",
      mapsDir: "",
      modsDir: "",
      replaysDir: "",
      gamePrefsPath: "",
      mapGeneratorDir: "",
      javaPath: "",
      winePrefix: "",
    },
  },
  social: { friends: [], foes: [], players: [], loginLookups: [] },
  streams: { live: [], status: { type: "idle" }, announced: [] },
  events: {
    catalogue: [],
    source: "bundled",
    submitUrl: "",
    status: { type: "idle" },
    view: "month",
    anchor: "",
    query: { text: "", category: null, origin: null, onlyReminders: false },
    selected: null,
  },
  coop: {
    scenarios: [],
    missions: [],
    catalogStatus: { type: "idle" },
    selectedMissionId: null,
    playerCount: 0,
    leaderboard: [],
    leaderboardStatus: { type: "idle" },
  },
  tourney: {
    events: [],
    assetBase: "",
    discord: "",
    status: { type: "idle" },
    selectedId: null,
    detail: null,
    detailStatus: { type: "idle" },
    pending: null,
    actionError: null,
    entrantProfiles: [],
    chatRooms: [],
    openRoomId: null,
    chatPosts: [],
    chatStatus: { type: "idle" },
    articles: [],
    hosting: { loggedIn: false, allowed: false, pending: false },
    accountSearch: { query: "", matches: [], status: { type: "idle" } },
    series: [],
    seriesStatus: { type: "idle" },
    openSeries: null,
    renames: null,
    renamesStatus: { type: "idle" },
    ratingCheck: null,
    ratingCheckStatus: { type: "idle" },
    playerRatings: null,
    playerRatingsStatus: { type: "idle" },
    pinnedRoomId: null,
    pinnedPosts: [],
    copySources: [],
    copySourcesStatus: { type: "idle" },
    copySource: null,
    copySourceStatus: { type: "idle" },
    presets: [],
    template: null,
    templateStatus: { type: "idle" },
    site: {
      account: {
        loggedIn: false,
        oauth: false,
        fafId: null,
        fafName: "",
        discord: "",
        editor: false,
        importer: false,
        director: false,
        siteAdmin: false,
        siteAdminAccount: false,
        adminStandDown: false,
        allowed: false,
      },
      pending: { items: [], requests: null, newRequests: null },
      hall: null,
      hallStatus: { type: "idle" },
      console: null,
      consoleStatus: { type: "idle" },
      editorAccess: { oauth: false, loggedIn: false, allowed: false, pending: false },
      importerAccess: { oauth: false, loggedIn: false, allowed: false, pending: false },
      articleImage: null,
    },
    descImage: null,
  },
  guides: {
    auth: { type: "signedOut" },
    submissions: [],
    status: { type: "idle" },
    write: { type: "idle" },
    submit: { type: "idle" },
    repo: "",
    settled: [],
  },
  training: {
    resources: [],
    trainers: [],
    status: { type: "idle" },
    source: "bundled",
    document: {
      resourceId: "",
      markdown: "",
      status: { type: "idle" },
      recording: "",
      recordingStatus: { type: "idle" },
    },
    links: {
      discordUrl: "",
      replayReviewChannel: "",
      replayReviewUrl: "",
      replayReviewCategory: null,
      contributeUrl: "",
      contributeCategory: null,
      wikiUrl: "",
    },
    query: EMPTY_TRAINING_QUERY,
    recommended: [],
    profile: {
      player: "",
      rating: null,
      ratings: {},
      gameModes: [],
      maps: [],
      factions: [],
      gamesSeen: 0,
    },
    selectedId: null,
    review: null,
    reviewPost: null,
    contribution: null,
    contributionPost: null,
  },
  tutorials: {
    categories: [],
    tutorials: [],
    status: { type: "idle" },
    selectedId: null,
    launch: { type: "idle" },
  },
  uploads: { request: null, status: { type: "idle" }, preview: "" },
  galacticWar: {
    status: { type: "idle" },
    installedVersion: null,
    versions: null,
    belowMinimum: false,
    statistics: null,
    statisticsStatus: { type: "idle" },
  },
  clientUpdate: {
    status: { type: "idle" },
    currentVersion: "",
    release: null,
    dismissedVersion: "",
    lastChecked: "",
  },
  changelog: {
    releases: [],
    status: { type: "idle" },
    selected: "",
    entries: {},
    entryStatus: { type: "idle" },
  },
  settings: {
    // Mirrors `impl Default for GeneratorOptions`, like the working copy above.
    mapGenerator: {
      version: null,
      spawnCount: 6,
      numTeams: 2,
      mapSize: 512,
      seed: "",
      generationType: "casual",
      symmetry: "",
      symmetries: [],
      style: "",
      styles: [],
      terrainStyle: "",
      terrainStyles: [],
      textureStyle: "",
      textureStyles: [],
      resourceStyle: "",
      resourceStyles: [],
      propStyle: "",
      propStyles: [],
      reclaimDensity: null,
      reclaimDensityMin: null,
      reclaimDensityMax: null,
      resourceDensity: null,
      resourceDensityMin: null,
      resourceDensityMax: null,
      numToGenerate: null,
      debug: false,
      visualize: false,
      previewPath: "",
      outputPath: "",
      commandLineArgs: "",
    },
    theme: "forgeDark",
    gamePath: "",
    replayGamePath: "",
    // Empty means "work it out": see `PathPreferences` in faf-domain.
    paths: {
      vaultDir: "",
      mapsDir: "",
      modsDir: "",
      replaysDir: "",
      gamePrefsPath: "",
      mapGeneratorDir: "",
      javaPath: "",
      winePrefix: "",
    },
    keptGeneratedMaps: [],
    matchmakerVetoes: [],
    mapPoolsSeen: [],
    avatarHistory: [],
    cacheInfo: { totalFiles: 0, totalSizeBytes: 0, versions: [] },
    general: { startPage: "news", autoLogin: true, rememberTypedEntries: false, filterMemory: "session" },
    appearance: {
      density: "comfortable",
      reduceMotion: false,
      uiScale: 100,
      gameTileColumns: 0,
      sidebarWidth: 224,
      hoverPanels: true,
      hoverOpenDelayMs: 500,
      hoverCloseDelayMs: 160,
      replayFlags: false,
      backgroundImage: "",
      backgroundDim: 60,
    },
    social: { playerNotes: [], replayNotes: [] },
    notifications: {
      enabled: true,
      desktop: true,
      desktopAllKinds: false,
      sound: true,
      // Chime everywhere but the found match, mirroring
      // `NotificationSoundChoices::default()` in
      // `crates/faf-domain/src/state/settings.rs`. The two are compared by the
      // reducer conformance fixture, so changing one without the other fails
      // CI rather than drifting quietly.
      sounds: {
        // The one graded default: a found match expires, and sounding like a
        // friend coming online is what the report was about. It is the Java
        // client's own match sound, which is what people know this event by.
        matchFound: "fafMatch",
        privateMessage: "chime",
        mention: "chime",
        friendOnline: "chime",
        friendOffline: "chime",
        friendPlaying: "chime",
        newCustomGame: "chime",
        gameFull: "alert",
        gameLaunched: "chime",
        reviewReminder: "chime",
        partyInvite: "chime",
        other: "chime",
      },
      // Mirrors NOTIFICATION_SOUND_CHOICE_VERSION. A stored file below this
      // has its match-found row moved onto the current default on load; see
      // `NotificationPreferences`' Deserialize.
      soundChoiceVersion: 2,
      notifyWhenFocused: false,
      toastPosition: "bottomLeft",
      matchFound: true,
      privateMessages: true,
      mentions: true,
      friendOnline: true,
      friendOffline: true,
      friendPlaying: true,
      newCustomGames: false,
      newCustomGamesFriendsOnly: true,
      gameFull: true,
      gameLaunched: true,
      reviewReminder: true,
      partyInvites: true,
      streamLive: true,
      mapGenerated: true,
      queueOpponentQueues: [],
      volume: 70,
      repeatCooldownSeconds: 2,
      mapPoolMutedQueues: [],
    },
    chat: {
      showJoinsParts: false,
      showTimestamps: true,
      use24HourTime: true,
      coloredNames: false,
      rosterWidth: 280,
      fontSize: 13,
      senderWidth: 116,
      nameColors: {
        selfColor: "#ffdd00",
        friends: "#87cefa",
        foes: "#dc143c",
        moderators: "#32cd32",
        admins: "#ba55d3",
        pings: "#ff8c00",
        players: {},
      },
      hideFoeMessages: true,
      visibleMessageLimit: 500,
      autoJoinChannels: [],
      autoJoinLanguageChannel: true,
      autoJoinNewbieChannel: true,
      newbieChannelGameThreshold: 50,
      mutedPlayers: [],
      hiddenRosterCategories: [],
      readMarkers: {},
    },
    game: {
      additionalArguments: [],
      launchWrapper: "",
      autoGenerateMaps: true,
      confirmDownloadsBeforeJoining: true,
      cacheLifetimeDays: 30,
      cacheSizeAlertGb: 10,
      cacheRollingBranches: false,
      pipeLiveReplay: false,
      keepGeneratedMaps: false,
      keepGeneratedMapsLimit: 0,
      steamPresence: false,
      borderlessWindow: false,
    },
    discord: { enabled: true, disallowJoins: false },
    connectivity: { adapter: "dynamic", hostAdapter: "java", selectionVersion: 2 },
    debug: {
      iceAdapterDebugWindow: false,
      iceAdapterInfoWindow: false,
      iceAdapterConsoleWindow: false,
      mapGeneratorWindow: false,
    },
    updates: { automatic: true, preRelease: true },
    browsing: {
      customGamesView: "tiles",
      replaysView: "tiles",
      liveReplayView: "list",
      customGamesBrowser: {
        sort: "players",
        sortReversed: false,
        hidePrivate: false,
        hideModded: false,
        hideUnranked: false,
        hideFoes: false,
        applyFilters: false,
        rules: [],
        columnWidths: [],
        columnOrder: [],
        detailWidth: 0,
        detailHidden: false,
      },
      matchmakerUnselectedQueues: [],
      matchmakerFactions: ["UEF", "Aeon", "Cybran", "Seraphim"],
      matchmakerChatWidth: 0,
      liveReplayFilters: {
        search: "",
        gameType: "",
        featuredMod: "",
        activePlayers: "",
        maxPlayers: "",
        hideModded: false,
        hideSinglePlayer: false,
        hideUnranked: false,
        friendsOnly: false,
      },
      hostGame: {
        title: "",
        featuredMod: "faf",
        visibility: "public",
        map: "",
        passwordEnabled: false,
        password: "",
        enforceRatingRange: false,
        ratingMin: 800,
        ratingMax: 1500,
      },
      hostCoop: {
        title: "",
        featuredMod: "faf",
        visibility: "public",
        map: "",
        passwordEnabled: false,
        password: "",
        enforceRatingRange: false,
        ratingMin: 800,
        ratingMax: 1500,
      },
      favoriteMaps: [],
      favoriteMods: [],
      mapVaultPreset: "recommended",
      modVaultPreset: "recommended",
      mapVaultSort: "",
      modVaultSort: "",
      vaultPageSize: 0,
      replayListColumns: [],
      replayListOrder: [],
      liveReplayColumns: [],
      liveReplayOrder: [],
      coopBoardColumns: [],
      matchmakerRecentColumns: [],
      matchmakerRecentOrder: [],
      matchmakerInviteColumns: [],
      matchmakerInviteOrder: [],
      modPresets: [],
      leaderboardRatingColumns: ["games", "updated"],
      leaderboardIncludeFormerNames: false,
      replayVaultPlayer: "",
      replayChatChannel: "",
      replayChatTransfers: "show",
      legacyStorageMigrated: false,
      rememberedFilters: {},
    },
    events: { weekStart: "monday", reminders: [] },
  },
};

interface AppStore {
  state: AppState;
  /** True only after the authoritative Rust snapshot has replaced defaults. */
  hydrated: boolean;
  /** Apply a backend event (the only state-changing path, mirrors the backend). */
  apply: (event: AppEvent) => void;
  /** Replace state with a backend snapshot (initial hydration). */
  hydrate: (state: AppState) => void;
}

export const useAppStore = create<AppStore>((set) => ({
  state: INITIAL,
  hydrated: false,
  apply: (event) => set((s) => ({ state: applyEvent(s.state, event) })),
  hydrate: (state) => set({ state, hydrated: true }),
}));
